= Recomendaciones de frameworks python.
Javier Le칩n (@jelitox) <jel1284@gmail.com>
v1.0, 2015-08-05
:toc:
:imagesdir: assets/images
:homepage: http://blog.javierleon.com.ve
:hp-tags: Blog,Personal,Python,Pyve
// Web page meta data.
:keywords: Blog, Javier Le칩n, IT, Devops, Desarrollo, Sysadmin, Social, Networks, emprendimiento, Pagina Oficial,
:description: Blog personal y Profesional, +
Ingeniero en Informatica, desarrollador y Administrador de Sistemas e infraestructura, +
Redes Sociales, facebook, instagram, twitter, pinterest +
proyectos de emprendimiento Freenlance, +
Pagina principal.

.{revdate}:  {revnumber} 


Luego de tantas charlas y debates en el canal de telegram de Pyve, la comunidad Python de venezuela, he logrado publicar ac치 un compendio de los mensajes m치s interesantes que se han generado sobre diferentes frameworks en python de hackers con mucha experiencia en el desarrollo de aplicaciones en diferentes herramientas de python.



Carlos Gustavo Ruiz, [29.07.15 09:58]
Interesante punto de vista sobre docker en producci칩n http://sirupsen.com/production-docker/

Carlos Gustavo Ruiz, [29.07.15 10:31]
hace un mes y tanto vi este video http://www.infoq.com/presentations/code-bugs-legacy-pitfalls

Carlos Gustavo Ruiz, [29.07.15 10:31]
y hoy consegu칤 este proyecto que permite hacer lo que muestra el pana http://quantifiedcode.github.io/code-is-beautiful/#

Carlos Gustavo Ruiz, [29.07.15 15:55]
http://www.oreilly.com/programming/free/files/functional-programming-python.pdf

Carlos Gustavo Ruiz, [29.07.15 15:56]
游녡libro gratis de O'Reilly

Cherny Berbes칤, [29.07.15 16:12]
este tambi칠n est치 gratis: http://chimera.labs.oreilly.com/books/1234000000754

unknown, [29.07.15 16:56]
http://inventwithpython.com/

Cherny Berbes칤, [29.07.15 17:28]
https://www.fullstackpython.com/

Alexis S치nchez, [31.07.15 14:59]
Live Streaming para de developers para developers https://www.livecoding.tv/

Edwind Richzendy Contreras Soto, [01.08.15 15:45]
#recurso http://www.sitepoint.com/10-time-saving-tips-pythonists/

Edwind Richzendy Contreras Soto, [01.08.15 15:47]
#recurso #libro http://www.deploypython.com/
















TIP: happy hacking!!!
