= Estrenando Nuevo Blog 
Javier León (@jelitox) <jel1284@gmail.com>
v1.0, 2015-02-13
:toc:
:imagesdir: assets/images
:homepage: http://blog.javierleon.com.ve
:hp-tags: Blog, Personal

//(Titulo)Ingresando Nuevamente a la Blogosfera
//=====================================
// Web page meta data.
:keywords: Blog, Javier León, IT, Devops, Desarrollo, Sysadmin, Social, Networks, emprendimiento, Pagina Oficial,
:description: Blog personal y Profesional, +
Ingeniero en Informatica, desarrollador y Administrador de Sistemas e infraestructura, +
Redes Sociales, facebook, instagram, twitter, pinterest +
proyectos de emprendimiento Freenlance, +
Pagina principal.


.{revdate}: AsciiDoc {revnumber} Released
************************************************************************
Read the link:CHANGELOG.html[CHANGELOG] for release highlights and a
full list of all additions, changes and bug fixes. Changes are
documented in the updated link:userguide.html[User Guide]. See the
link:INSTALL.html[Installation page] for downloads and and
installation instructions.

'Stuart Rackham'
************************************************************************

Introduction
------------
{description}

AsciiDoc is highly configurable: both the AsciiDoc source file syntax
and the backend output markups (which can be almost any type of
SGML/XML markup) can be customized and extended by the user.

AsciiDoc is free software and is licenced under the terms of the 'GNU
General Public License version 2' (GPLv2).

TIP: The pages you are reading were written using AsciiDoc, to view
the corresponding AsciiDoc source click on the *Page Source* menu item
in the left hand margin.

