= Estrenando Nuevo Blog 
Javier León (@jelitox) <jel1284@gmail.com>
v1.0, 2015-02-13
:toc:
:imagesdir: assets/images
:homepage: http://blog.javierleon.com.ve


Ingresando Nuevamente a la Blogosfera
=====================================
// Web page meta data.
:keywords: AsciiDoc, DocBook, EPUB, PDF, ebooks, slideshow, slidy, man page
:description: AsciiDoc is a text document format for writing notes, +
documentation, articles, books, ebooks, slideshows, +
web pages, man pages and blogs. AsciiDoc files can be +
translated to many formats including HTML, PDF, EPUB, +
man page.


.{revdate}: AsciiDoc {revnumber} Released
************************************************************************
Read the link:CHANGELOG.html[CHANGELOG] for release highlights and a
full list of all additions, changes and bug fixes. Changes are
documented in the updated link:userguide.html[User Guide]. See the
link:INSTALL.html[Installation page] for downloads and and
installation instructions.

'Stuart Rackham'
************************************************************************

Introduction
------------
{description}

AsciiDoc is highly configurable: both the AsciiDoc source file syntax
and the backend output markups (which can be almost any type of
SGML/XML markup) can be customized and extended by the user.
